### ISSUE TITLE
Idk how to run locally your website

### ISSUE THREAD

**Issue by SNEAXIII** [Kienlabadao/COC-Damage-Calculator#5]
Hello, I am a junior backend developer and I want to help you to code your website.
As you don't explain how to run your website, I just can't test what I am doing.
Can you explain how to run it ? Tysm for your great work :)

**Comment by SNEAXIII** [comment]
Here is a small commit, what do you think ?
https://github.com/Kienlabadao/COC-Damage-Calculator/compare/main...SNEAXIII:COC-Damage-Calculator:basic-refactor

**Comment by Kienlabadao** [comment]
I'm using vscode with live server extension, so I can run the website locally (while live update every time I make change to the file). Another way is you can host it on github, but you probably will have to update some of the redirect link in order for it to work.

![image](https://github.com/user-attachments/assets/f36f09bf-27eb-429b-94e6-f4cae1d56da0)

**Comment by SNEAXIII** [comment]
Thanks buddy :)

**Comment by SNEAXIII** [comment]
Look at my PR ^^
